### ISSUE TITLE
Running task list for MVP

### ISSUE THREAD

**Issue by Oceanswave** [beyond-sharepoint/sp-lookout#1]
Pages:
- [x] Delete page on page settings
- [x] Add confirm dialog to delete page
- [x] Support WebPart Chrome/Color customization
- [x] Allow for easy duplication of web parts.
- [x] ~~Support sub-pages~~ _out of scope for this iteration, Office Nav UI is troublesome_
- [x] ~~Support page 'types' -- may include static (action), card, list, form, etc...~~ _out of scope for this iteration, pages need rethinking_
- [x] Support page customization. Background color, image...
- [x] Make Pages responsive
  - [x] Allow user-specified Breakpoints and columns per breakpoint
  - [x] Allow webparts to be organized at each breakpoint independently.
- [x] Persist collapsed sidebar state
- [x] Resize current page on sidebar resize

WebParts:
- [x] Better implementation of WebParts (make base abstract, provide for generic prop types, etc.)
- [x] Make asScriptedWebPart high order component
- [x] Make asAutoRefreshingWebPart high order component
- [x] Add External Image Web Part
- [x] Add BaristaBase Web Part... et.al. (Big task to get to MVP)
- [x] Add Action (button) web parts that invoke SPFiddle Scripts
- [x] ~~Add dynamic form web part based on Json Schema.~~ _out of scope for this iteration, pages ui doesn't really support this_
  - [x] ~~Add utility function to sp-lookout module to convert list field settings to Json schema~~
- [x] ~~Add tasks web part that works much like Github Tasks.~~ _out of scope for this iteration, nice to have_
- [x] ~~Social Media WebParts (Twitter, Instagram, Facebook...)~~ _out of scope for this iteration, nice to have_

Folder View:
- [x] ~~File/Folder Context Menu on Right Click -- use react-context-menu. Support copy/paste/export other functionality~~ _out of scope for this iteration, nice to have_
- [x] Handle Quick Actions (star/lock) on files better (they're still being rendered even if not selected)

Fiddle Functionality:
- [x] Support importing modules from SP Lookout
  - [x] Create AST visitor that locates imports that start from relative path
  - [x] Resolve the import to an 'absolute' path in the virtual file system
  - [x] Add the imported items to the brew request.
  - [x] Do the above recursively for each import
- [x] Add a SP-Lookout built-in module
  - [x] Add to list of auto-imports to the relative app path.
  - [x] Add ability to get parameters that Web Parts pass, also, UI to specify test params in fiddle.
  - [x] Add ability to get/set local storage living in proxy origin
  - [ ] Add ability to get 'secrets' defined in the application ( oauth keys and so forth )
  - [x] Add shortcut method for postProgress
- [x] Support auto-complete on module imports
- [ ] Add ability to determine all exports and their types that a fiddle has
  - [ ] Add AST visitor that examines export statements and records the name and type (Name definitely proofed out, not sure how to get 'type'
  - [ ] Modify scripted web part settings to filter out scripts that don't have the appropriate export types
- [x] ~~Refactor FiddlesStore to use folder/filename as hashkey~~ _out of scope - Array structure is fine_
- [x] Expose Require Config in the UI
- [x] Refactor imports/scripts/definitions loading to get local resources to minimize async requests ~~(might require ejecting and using raw-loader)~~ using forked react-scripts-ts hosted on GH

Proxy/Worker:
- [x] Make the commands extensible
- [x] Make the worker commands extensible
- [x] Reduce HostWebProxy file size by offloading commands to parent as much as possible
- [x] Create a better worker bootstrap so that other module loaders could potentially be used.

Data/Persistence:
- [x] Separate out the different stores and put them behind an interface with specific implementations

Example/Demo/Etc:
- [x] Add animated gif to readme.md
- [x] Refactor examples to make it easier to add new examples.
- [ ] Add a examples to populate a SharePoint dev tenant with sample data. (e.g. InfoPath Forms, files, et. al. Use Faker and previous creation code.
- [x] ~~Social Media/News Page~~ _nice to have_
- [ ] SharePoint Governance Page
  - [ ] Create a treeview/starburst view of current SharePoint storage usage
  - [ ] Broken Inheritance (Items) - Display List of Lists that contain items that have broken inheritance sorted by # of broken items descending - expand to see actual items.
  - [ ] Doc Libs with items that have large number of versions

General/Uncategorized:
- [x] ~~Add ability for multiple named SharePoint connections to be defined.~~ _out of scope for this iteration, focus changing_
  - [x] ~~Add ability to specify which named connection should be used (both for fiddle and pages)~~ _out of scope for this iteration, focus changing_
- [x] Troubleshoot auth issues on iOS Safari
  - [x] Troubleshoot lack of Nav Component
- [x] Edge/IE11 testing.
  - [ ] MS Edge
    - [x] Troubleshoot auth issues
    - [x] Troubleshoot flexboxes popping in and out of rendering
    - [x] Troubleshoot Unexpected content type error
    - [ ] Troubleshoot data clone error on fetch responses
    - [ ] Troubleshoot error clones
  - [ ] Internet Explorer 11
     - [x] Troubleshoot flexbox issues
     - [x] Troubleshoot lack of Nav component
     - [ ] Troubleshoot data clone error on fetch responses
     - [ ] Troubleshoot execution of promises
